### PR TITLE
System Roles should consistently use ansible_managed in configuration files it manages

### PR DESCRIPTION
**Pull request by nhosoi**
bz#2044640

The mssql role creates a config file mssql.conf. This commit adds
the ansible managed header to the file using {{ ansible_managed }}.

Example of mssql.conf:
```
# BEGIN ANSIBLE MANAGED BLOCK
#
# Ansible managed
#
# END ANSIBLE MANAGED BLOCK
[sqlagent]
enabled = false
```

### CODE REVIEW

**Review by spetrosi — APPROVED** [review]
lgtm

**Review by richm — APPROVED** [review]
lgtm

**Comment by nhosoi** [comment]
Thank you for your reviews, @spetrosi and @richm.
(And thanks to @spetrosi for the model to follow in his postfix pr.)
Since I do not have the right to merge, may I ask you to do it? Thanks! 

Side note:
The failures in some fedora related composes in tests_upgrade_2017.yml are from the lack of the disk space.
```
TASK [fedora.linux_system_roles.mssql : Ensure the mssql-server package] *******
task path: /tmp/tmp5qh9d5k1/ansible_collections/fedora/linux_system_roles/roles/mssql/tasks/main.yml:100
Wednesday 23 February 2022  07:58:53 +0000 (0:00:00.451)       0:02:26.152 **** 
fatal: [/cache/fedora-35.qcow2]: FAILED! => {
    "changed": false,
    "failures": [],
    "rc": 1,
    "results": []
}
MSG:
Unknown Error occurred: Transaction test error:
  installing package mssql-server-15.0.4198.2-10.x86_64 needs 98MB more space on the / filesystem
Error Summary
-------------
Disk Requirements:
   At least 98MB more space needed on the / filesystem.
```

**Comment by richm** [comment]
>  The failures in some fedora related composes in tests_upgrade_2017.yml are from the lack of the disk space.

Yes, that is a known problem with the way we use and provision qcow2 images.  You can ignore it.

**Pull request merged**
