### PR TITLE
use tox-lsr 2.2.0

### PR DESCRIPTION
**Pull request by nhosoi**
Upgrade to tox-lsr 2.2.0 to pick up fix for improving collection
testing to get rid of black.

### CODE REVIEW

**Comment by spetrosi** [comment]
@nhosoi why does the python 3.6 tox check still fail? The same happened to #2 that only changed README.

**Comment by spetrosi** [comment]
@richm I need access to be able to merge to this repo. Can you give me the permissions?

**Comment by richm** [comment]
> @richm I need access to be able to merge to this repo. Can you give me the permissions?

ok - try it now

**Comment by richm** [comment]
> @richm I need access to be able to merge to this repo. Can you give me the permissions?

Need to update molecule/default/molecule.yml - to support moleculev3 - as in https://github.com/linux-system-roles/template/pull/62

**Comment by nhosoi** [comment]
> @nhosoi why does the python 3.6 tox check still fail? The same happened to #2 that only changed README.

Hi @spetrosi, it looks "tox -e molecule" is failing due to lacking `molecule`.
@richm, do you happen to know the issue is being fixed in some other pr?

**Comment by richm** [comment]
> @nhosoi why does the python 3.6 tox check still fail? The same happened to #2 that only changed README.

Need to update molecule/default/molecule.yml - to support moleculev3 - as in linux-system-roles/template#62

**Comment by spetrosi** [comment]
Thanks @richm, I can merge now but will wait for checks fixes.

**Comment by richm** [comment]
@nhosoi please include the molecule/default/molecule.yml change from https://github.com/linux-system-roles/template/pull/62 in this PR

**Comment by nhosoi** [comment]
> > @nhosoi why does the python 3.6 tox check still fail? The same happened to #2 that only changed README.
> 
> Need to update molecule/default/molecule.yml - to support moleculev3 - as in [linux-system-roles/template#62](https://github.com/linux-system-roles/template/pull/62)

Thanks, @richm! May we ask @spetrosi to fix it?

**Comment by spetrosi** [comment]
I am very willing to @nhosoi, will try

**Comment by richm** [comment]
The upgrade to tox-lsr 2.x and the fix to molecule/default/molecule.yml must happen in the same PR, or you will still get tox test failures.
If you only change molecule/default/molecule.yml, then tox will use molecule v2 because that's what tox-lsr 1.x uses

**Comment by nhosoi** [comment]
> The upgrade to tox-lsr 2.x and the fix to molecule/default/molecule.yml must happen in the same PR, or you will still get tox test failures.
> If you only change molecule/default/molecule.yml, then tox will use molecule v2 because that's what tox-lsr 1.x uses

I see... Then, let me do it in this pr. (Sorry for the noise, @spetrosi ...)

**Comment by spetrosi** [comment]
@nhosoi, I've already pushed a commit that fixes this to this PR. Waiting for the checks results now.

**Comment by richm** [comment]
> I see... Then, let me do it in this pr. (Sorry for the noise, @spetrosi ...)

Well, looks like @spetrosi already did it

**Comment by nhosoi** [comment]
> > I see... Then, let me do it in this pr. (Sorry for the noise, @spetrosi ...)
> 
> Well, looks like @spetrosi already did it

Ok. I've made the change, but the molecule test run locally on my laptop fails... Both "docker" and "podman" are not allowed... *puzzled*
```
+ python /home/nhosoi/tmp/working-lsr/mssql/.tox/molecule/bin/molecule test -s default
8<------------------->8
CRITICAL Failed to pre-validate.

{'driver': [{'name': ['unallowed value podman']}]}
ERROR: InvocationError for command /usr/bin/bash /home/nhosoi/.local/lib/python3.8/site-packages/tox_lsr-2.2.0-py3.8.egg/tox_lsr/test_scripts/runsyspycmd.sh molecule test -s default (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   molecule: commands failed

```

**Comment by richm** [comment]
@nhosoi if you are using tox-lsr 2.x on your laptop, you'll need the molecule/default/molecule.yml fix too

**Review by richm — APPROVED** [review]
lgtm

**Comment by nhosoi** [comment]
> @nhosoi if you are using tox-lsr 2.x on your laptop, you'll need the molecule/default/molecule.yml fix too

Yeah, that's what I did, I thought. But there must be some mistakes. Anyway, I'm happy with the fix by @spetrosi. Ship it!

**Pull request merged**
