### PR TITLE
Replace FQDN with short names when configuring availability group

### LINKED ISSUE #85: Using role to setup SQL Server availability group clustering not working if FQDN hostnames are used in inventory
If FQDN hostnames are used in the inventory to setup a SQL Server availability group, the resulting cluster does not work properly.  The SQL error log shows seeding errors on one of the nodes and "pcs status" never stabilizes.  

When using short host names in the inventory, everything appears to work correctly.

### PR DESCRIPTION
**Pull request by spetrosi**
Fixes #85

### CODE REVIEW

**Comment by richm** [comment]
Does this impose additional name resolution requirements e.g. need to configure DNS or /etc/hosts with both short names and fqdns?
Does this impose additional x509 cert generation requirements e.g. need to have both short names and fqdn in either the cert subject or Subject Alt Name?

**Comment by spetrosi** [comment]
> Does this impose additional name resolution requirements e.g. need to configure DNS or /etc/hosts with both short names and fqdns? Does this impose additional x509 cert generation requirements e.g. need to have both short names and fqdn in either the cert subject or Subject Alt Name?

There are requirements for name resolution indeed, thank you for bringing this up. MS docs list their requirements here: https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-availability-group-configure-ha?view=sql-server-ver15#prerequisites
I need to link to this document from the readme.
Configuring both short names and fqdns must be fine, the most important thing is to have short names.
I do not know about additional x5099 cert requirements, I do not think so. The requirement for short names comes from Microsoft, I guess they would mentiont if so.

**Comment by richm** [comment]
Yeah, it doesn't say anything about the certs - it uses sql to generate some sort of certificates, so perhaps it hides that.  If we're using that method to generate the certs, then we don't have to mention it.

**Review by richm — APPROVED** [review]

**Comment by spetrosi** [comment]
I discussed this with Amit from Microsoft, and he says that using FQDN for endpoint URLs is recommended, so I will stick to it. Will then check how it goes with Brian. I will keep changes to readme.

**Comment by richm** [comment]
> Hi @spetrosi, when I ran in to this issue, in my /etc/hosts file on the hosts, I had both FQDN and short names:
> 
> 192.168.0.131 r8-server1.example.com r8-server1 192.168.0.132 r8-server2.example.com r8-server2 192.168.0.133 r8-server3.example.com r8-server3 192.168.0.134 r8-server4.example.com r8-server4
> 
> But if I used the FQDN in the Ansible inventory file, I ran in to the previously discussed issues.

What happens if the shortnames come first e.g.
```
192.168.0.131 r8-server1 r8-server1.example.com
```
?

**Comment by briansmith0** [comment]
@richm I would need to re-setup my environment to try that out, and I'm not sure how soon I would be able to get that setup again.  The "hosts"(5) man page indicates that the shorter name should be an alias (i.e. not the first entry), and the example in the man page has FQDN listed first, then short name, as I had configured.

**Comment by richm** [comment]
> @richm I would need to re-setup my environment to try that out, and I'm not sure how soon I would be able to get that setup again. The "hosts"(5) man page has an example with the FQDN listed first, then short name, as I had configured.

If I recall, the order can affect how entries are returned and used by the calling application.

**Comment by briansmith0** [comment]
@richm @spetrosi using the latest mssql role from Galaxy, I tried this again.  When using short names in the Ansible inventory file, everything appears to works properly.  

When using FQDNs in the Ansible inventory file, with this /etc/hosts file on each node:

192.168.0.131 r8-server1 r8-server1.example.com
192.168.0.132 r8-server2 r8-server2.example.com
192.168.0.133 r8-server3 r8-server3.example.com
192.168.0.134 r8-server4 r8-server4.example.com

The cluster does not come up properly:

[root@r8-server2 ~]# pcs status
Cluster name: ag1
Cluster Summary:
  * Stack: corosync
  * Current DC: r8-server2.example.com (version 2.1.2-4.el8_6.2-ada5c3b36e2) - partition with quorum
  * Last updated: Mon Aug 22 08:18:56 2022
  * Last change:  Mon Aug 22 08:14:53 2022 by root via cibadmin on r8-server2.example.com
  * 3 nodes configured
  * 4 resource instances configured

Node List:
  * Online: [ r8-server2.example.com r8-server3.example.com r8-server4.example.com ]

Full List of Resources:
  * virtualip	(ocf::heartbeat:IPaddr2):	 Started r8-server4.example.com
  * Clone Set: ag_cluster-clone [ag_cluster] (promotable):
    * ag_cluster	(ocf::mssql:ag):	 FAILED Master r8-server4.example.com (Monitoring)
    * ag_cluster	(ocf::mssql:ag):	 FAILED r8-server2.example.com (Monitoring)
    * ag_cluster	(ocf::mssql:ag):	 FAILED r8-server3.example.com (Monitoring)

Failed Resource Actions:
  * ag_cluster_monitor_11000 on r8-server4.example.com 'not running' (7): call=105, status='complete', last-rc-change='Mon Aug 22 08:18:55 2022', queued=0ms, exec=5919ms
  * ag_cluster_monitor_12000 on r8-server2.example.com 'not running' (7): call=86, status='complete', last-rc-change='Mon Aug 22 08:18:55 2022', queued=0ms, exec=5613ms
  * ag_cluster_monitor_12000 on r8-server3.example.com 'not running' (7): call=79, status='complete', last-rc-change='Mon Aug 22 08:18:55 2022', queued=0ms, exec=5508ms

Daemon Status:
  corosync: active/enabled
  pacemaker: active/enabled
  pcsd: active/enabled
  sbd: active/enabled

**Comment by spetrosi** [comment]
Hi @briansmith0, I wonder if the issue is in the ha_cluster role trying to guess the names that you want to use.
When running this role against beaker systems, I needed to provide short node names in the inventory. Also, I set up a private network on beaker to have a virtualip reserved, so provided my custom IP addresses too. The resulting inventory looked like this:
```
all:
  hosts:
    isvqe-01.example.com:
      ansible_user: root
      mssql_ha_replica_type: primary
      ha_cluster:
        node_name: isvqe-01
        pcs_address: isvqe-01
        corosync_addresses:
          - 192.168.100.107
    veritas6.example.com:
      ansible_user: root
      mssql_ha_replica_type: synchronous
      ha_cluster:
        node_name: veritas6
        pcs_address: veritas6
        corosync_addresses:
          - 192.168.100.103
    veritas7.example.com:
      ansible_user: root
      mssql_ha_replica_type: witness
      ha_cluster:
        node_name: veritas7
        pcs_address: veritas7
        corosync_addresses:
          - 192.168.100.105
```

**Comment by spetrosi** [comment]
Galaxy still have the initial HA version, I am planning to publish new version to galaxy tomorrow, For now, I recommend you trying with the repo. You will be able to do this to setup DB and then setup HA:
```
    - name: Set facts to create a test DB on primary as a pre task
      set_fact:
        mssql_pre_input_sql_file: create_example_db.j2
        __mssql_test_db_name: "{{ mssql_ha_db_name }}"
      when: mssql_ha_replica_type == 'primary'

    - name: Run on all hosts to configure HA cluster
      include_role:
        name: linux-system-roles.mssql
```

**Comment by briansmith0** [comment]
Hi @spetrosi thanks for the info, with this inventory file it seemed to work:

all:
  hosts:
    r8-server2.example.com:
      mssql_ha_replica_type: primary
      ha_cluster:
        node_name: r8-server2
        pcs_address: r8-server2
    r8-server3.example.com:
      mssql_ha_replica_type: synchronous
      ha_cluster:
        node_name: r8-server3
        pcs_address: r8-server3
    r8-server4.example.com:
      mssql_ha_replica_type: synchronous
      ha_cluster:
        node_name: r8-server4
        pcs_address: r8-server4

Is this possibly a bug in the ha_cluster role, or is this the intended behavior?  Based on the HA cluster documentation it looks like you should be able to use a FQDN for the node name:  https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/configuring_and_managing_high_availability_clusters/index

**Comment by spetrosi** [comment]
ha_cluster by default uses inventory hostnames for node names and pcs addresses. And I suppose in our case we need short addresses.
Did you run your test that succeed with the new role version or with the same version that you run the test that failed?

**Comment by briansmith0** [comment]
@spetrosi this testing was done with the galaxy version.  If there is a requirement for the SQL role to use short names, can we document this in the README.md?  Thanks again for your help with this issue!

**Comment by spetrosi** [comment]
@briansmith0 of course, it's wip in #92, I'll add it as a hard requirement.

**Pull request merged**
