### PR TITLE
Make it possible to intput multiple file with loop internaly

### PR DESCRIPTION
**Pull request by spetrosi**

### CODE REVIEW

**Review by richm — APPROVED** [review]

**Comment by spetrosi** [comment]
[citest]

**Comment by spetrosi** [comment]
[citest]

**Comment by spetrosi** [comment]
[citest]

**Comment by spetrosi** [comment]
[citest pending]

**Comment by spetrosi** [comment]
[citest]

**Comment by spetrosi** [comment]
Results of performance improvement:
Local VM improved performance: 10m7.851s
Local VM previous performance: 11m36.853s
Result: 12.8% faster

**Pull request merged**
