### PR TITLE
ansible-lint - use changed_when for conditional tasks; fix spacing

### PR DESCRIPTION
**Pull request by richm**
ansible-lint now requires the use of changed_when even for
conditional tasks

Fix some jinja spacing issues

add skip for `galaxy[no-runtime]`

remove deprecated suppression comment

add pipefail for shell

add yaml header for vault-variables.yml

Signed-off-by: Rich Megginson <rmeggins@redhat.com>

### CODE REVIEW

**Comment by richm** [comment]
[citest]

**Comment by spetrosi** [comment]
[citest pending]

**Comment by richm** [comment]
not sure what the rhel7 ansible 2.9 failures are - cannot reproduce locally - I'm inclined to say they are not related to the ansible-lint changes

**Comment by spetrosi** [comment]
> not sure what the rhel7 ansible 2.9 failures are - cannot reproduce locally - I'm inclined to say they are not related to the ansible-lint changes

Yes, not related

**Pull request merged**
