### PR TITLE
tests: Fix HA tests

### PR DESCRIPTION
**Pull request by spetrosi**
Enhancement:
* Remove extrainvocation of read-scale test
* Add example inventories
* Run configure_ha_cluster_reaad_scale test only when invntory has 3 nodes and zero witness nodes

### CODE REVIEW

**Comment by spetrosi** [comment]
[citest]

**Review by richm — APPROVED** [review]

**Comment by spetrosi** [comment]
[citest]

**Comment by spetrosi** [comment]
[citest]

**Comment by spetrosi** [comment]
[citest]

**Comment by spetrosi** [comment]
[citest]

**Pull request merged**
