### PR TITLE
Enable running in series

### PR DESCRIPTION
**Pull request by spetrosi**
This can be used in gating to run tests in this order:

1. $ROLE_TEST_PATH/tests_*_2017.yml
2. $ROLE_TEST_PATH/tests_2019_upgrade.yml
3. $ROLE_TEST_PATH/tests_*_2019.yml
4. $ROLE_TEST_PATH/tests_2022_upgrade.yml
5. $ROLE_TEST_PATH/tests_*_2022.yml

### CODE REVIEW

**Comment by spetrosi** [comment]
[citest]

**Review by richm — APPROVED** [review]

**Comment by ukulekek** [comment]
[citest failed]

**Comment by spetrosi** [comment]
[citest]

**Comment by ukulekek** [comment]
[citest failed]

**Comment by ukulekek** [comment]
[citest pending]

**Comment by spetrosi** [comment]
[citest failed]

**Pull request merged**
