### PR TITLE
Not restart the mssql server when it is being started or stopped.

### PR DESCRIPTION
**Pull request by nhosoi**

### CODE REVIEW

**Comment by nhosoi** [comment]
I could reproduce the problem without using ansible-playbook with this brutal manner. :)

I ran this command line in two windows.
```
# systemctl restart mssql-server & systemctl restart mssql-server & systemctl restart mssql-server & systemctl restart mssql-server & systemctl restart mssql-server
```
Then, it hit some critical timing and a `systemctl stop mssql-server` hung.
```
# systemctl status mssql-server
● mssql-server.service - Microsoft SQL Server Database Engine
   Loaded: loaded (/usr/lib/systemd/system/mssql-server.service; enabled; vendor preset: disabled)
   Active: deactivating (stop-sigterm) since Thu 2022-03-10 18:05:42 EST; 23min ago
     Docs: https://docs.microsoft.com/en-us/sql/linux
 Main PID: 30731 (sqlservr)
    Tasks: 144
   Memory: 747.5M
   CGroup: /system.slice/mssql-server.service
           ├─30731 /opt/mssql/bin/sqlservr
           └─30734 /opt/mssql/bin/sqlservr
```
Here's the snippet of journalctl.
```
# journalctl -u mssql-server
Mar 10 18:04:54 localhost.localdomain sqlservr[30564]: [71B blob data]
Mar 10 18:04:54 localhost.localdomain sqlservr[30564]: [124B blob data]
Mar 10 18:05:40 localhost.localdomain systemd[1]: Stopping Microsoft SQL Server Database Engine...
Mar 10 18:05:40 localhost.localdomain sqlservr[30564]: [200B blob data]
Mar 10 18:05:40 localhost.localdomain sqlservr[30564]: [190B blob data]
Mar 10 18:05:40 localhost.localdomain sqlservr[30564]: [73B blob data]
Mar 10 18:05:40 localhost.localdomain sqlservr[30564]: [164B blob data]
Mar 10 18:05:41 localhost.localdomain sqlservr[30564]: [1B blob data]
Mar 10 18:05:41 localhost.localdomain systemd[1]: mssql-server.service: Succeeded.
Mar 10 18:05:41 localhost.localdomain systemd[1]: Stopped Microsoft SQL Server Database Engine.
Mar 10 18:05:41 localhost.localdomain systemd[1]: Started Microsoft SQL Server Database Engine.
Mar 10 18:05:42 localhost.localdomain systemd[1]: Stopping Microsoft SQL Server Database Engine...
Mar 10 18:05:43 localhost.localdomain sqlservr[30734]: 2022-03-10 18:05:43.49 Server      Microsoft SQL Server >
Mar 10 18:05:43 localhost.localdomain sqlservr[30734]: [29B blob data]
Mar 10 18:05:43 localhost.localdomain sqlservr[30734]: [49B blob data]
```
If you run `systemctl stop mssql-server`, then the process is piled up.
```
# ps -ef | grep mssql
mssql      30731       1  0 18:05 ?        00:00:00 /opt/mssql/bin/sqlservr
mssql      30734   30731  4 18:05 ?        00:01:20 /opt/mssql/bin/sqlservr
root       30914   28101  0 18:08 pts/0    00:00:00 systemctl stop mssql-server
root       30953   28101  0 18:10 pts/0    00:00:00 systemctl stop mssql-server
root       31158   28135  0 18:32 pts/1    00:00:00 systemctl stop mssql-server
```
Unless you kill them manually, the processes stay until it times out (in 30 minutes by default).
```
● mssql-server.service - Microsoft SQL Server Database Engine
   Loaded: loaded (/usr/lib/systemd/system/mssql-server.service; enabled; vendor preset: disabled)
   Active: failed (Result: timeout) since Thu 2022-03-10 18:35:42 EST; 37s ago
     Docs: https://docs.microsoft.com/en-us/sql/linux
  Process: 30731 ExecStart=/opt/mssql/bin/sqlservr (code=killed, signal=KILL)
 Main PID: 30731 (code=killed, signal=KILL)
    Tasks: 0
   Memory: 96.0K
   CGroup: /system.slice/mssql-server.service
```

**Comment by richm** [comment]
> I could reproduce the problem without using ansible-playbook with this brutal manner. :)
> 
> I ran this command line in two windows.
> 
> ```
> # systemctl restart mssql-server & systemctl restart mssql-server & systemctl restart mssql-server & systemctl restart mssql-server & systemctl restart mssql-server
> ```

Can you do this with rsyslog?

**Comment by nhosoi** [comment]
> Can you do this with rsyslog?

rsyslog has no problem. My repeated attempts finished ok. It seems it handles the startup and shutdown in the atomic style. I don't see the race/wrongly ordered stop and start in the log. So, I guess `systemctl` thinks each server/daemon/service is responsible on the behavior...
```
Mar 11 11:41:21 localhost rsyslogd[7937]: [origin software="rsyslogd" swVersion="8.1911.0-7.el8" x-pid="7937" x-info="https://www.rsyslog.com"] start
Mar 11 11:41:21 localhost systemd[1]: Started System Logging Service.
Mar 11 11:41:21 localhost rsyslogd[7937]: imjournal: journal files changed, reloading...  [v8.1911.0-7.el8 try https://www.rsyslog.com/e/0 ]
Mar 11 11:41:21 localhost systemd[1]: Stopping System Logging Service...
Mar 11 11:41:21 localhost rsyslogd[7937]: [origin software="rsyslogd" swVersion="8.1911.0-7.el8" x-pid="7937" x-info="https://www.rsyslog.com"] exiting on signal 15.
Mar 11 11:41:21 localhost systemd[1]: rsyslog.service: Succeeded.
Mar 11 11:41:21 localhost systemd[1]: Stopped System Logging Service.
Mar 11 11:41:21 localhost systemd[1]: Starting System Logging Service...
Mar 11 11:41:21 localhost rsyslogd[7958]: [origin software="rsyslogd" swVersion="8.1911.0-7.el8" x-pid="7958" x-info="https://www.rsyslog.com"] start
Mar 11 11:41:21 localhost systemd[1]: Started System Logging Service.
Mar 11 11:41:21 localhost rsyslogd[7958]: imjournal: journal files changed, reloading...  [v8.1911.0-7.el8 try https://www.rsyslog.com/e/0 ]
Mar 11 11:41:42 localhost systemd[1]: Stopping System Logging Service...
Mar 11 11:41:42 localhost rsyslogd[7958]: [origin software="rsyslogd" swVersion="8.1911.0-7.el8" x-pid="7958" x-info="https://www.rsyslog.com"] exiting on signal 15.
Mar 11 11:41:42 localhost systemd[1]: rsyslog.service: Succeeded.
Mar 11 11:41:42 localhost systemd[1]: Stopped System Logging Service.
Mar 11 11:41:42 localhost systemd[1]: Starting System Logging Service...
Mar 11 11:41:42 localhost rsyslogd[7981]: [origin software="rsyslogd" swVersion="8.1911.0-7.el8" x-pid="7981" x-info="https://www.rsyslog.com"] start
Mar 11 11:41:42 localhost systemd[1]: Started System Logging Service.
Mar 11 11:41:42 localhost rsyslogd[7981]: imjournal: journal files changed, reloading...  [v8.1911.0-7.el8 try https://www.rsyslog.com/e/0 ]
Mar 11 11:41:42 localhost systemd[1]: Stopping System Logging Service...
Mar 11 11:41:42 localhost rsyslogd[7981]: [origin software="rsyslogd" swVersion="8.1911.0-7.el8" x-pid="7981" x-info="https://www.rsyslog.com"] exiting on signal 15.
Mar 11 11:41:42 localhost systemd[1]: rsyslog.service: Succeeded.
Mar 11 11:41:42 localhost systemd[1]: Stopped System Logging Service.
Mar 11 11:41:42 localhost systemd[1]: Starting System Logging Service...
Mar 11 11:41:42 localhost systemd[1]: rsyslog.service: Succeeded.
Mar 11 11:41:42 localhost systemd[1]: Stopped System Logging Service.
Mar 11 11:41:42 localhost systemd[1]: Starting System Logging Service...
Mar 11 11:41:42 localhost systemd[1]: rsyslog.service: Succeeded.
Mar 11 11:41:42 localhost systemd[1]: Stopped System Logging Service.
Mar 11 11:41:42 localhost systemd[1]: Starting System Logging Service...
Mar 11 11:41:42 localhost rsyslogd[8006]: [origin software="rsyslogd" swVersion="8.1911.0-7.el8" x-pid="8006" x-info="https://www.rsyslog.com"] start
Mar 11 11:41:42 localhost systemd[1]: Started System Logging Service.
Mar 11 11:41:42 localhost rsyslogd[8006]: imjournal: journal files changed, reloading...  [v8.1911.0-7.el8 try https://www.rsyslog.com/e/0 ]
```

**Comment by richm** [comment]
> rsyslog has no problem. My repeated attempts finished ok. It seems it handles the startup and shutdown in the atomic style. I don't see the race/wrongly ordered stop and start in the log. So, I guess systemctl thinks each server/daemon/service is responsible on the behavior...

Is there a bug in the mssql.service file?  not sure where it is installed - /usr/lib/systemd/system/mssql.service or /etc/systemd/system/mssql.service or somewhere else?

I'm not aware of anything in rsyslogd that has logic to "prevent multiple instances of service from running" - so maybe it is in the .service file

**Comment by spetrosi** [comment]
I'll inform MS folks about this, this looks like a mssql-server.service bug to me.

**Comment by nhosoi** [comment]
> I'll inform MS folks about this, this looks like a mssql-server.service bug to me.

Thank you, @spetrosi ! I'd think this pr is not needed once it's solved in the service. Closing...

**Pull request closed without merging**
